config/routes.rb
Rails.application.routes.draw do
  resources :vendors

  resources :items

  get "search" => "search#index"

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :category, :presence=>true
	validates :price, :presence => true,
            :numericality => true,
            :format => { :with => /\A\d{1,4}(\.\d{0,2})?\z/ } 
	enum category: ['Accessories', 'Battery', 'Juice', 'Mods', 'Starter Kits', 'Tanks / Attys']

	default_scope { order("lower(name) asc")}


	belongs_to :vendor
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	validates :name, :presence => true
	validates :email, :uniqueness => true
 	validates_format_of :email, :with => /@/

 	default_scope { order("lower(name) asc")}
 	
 	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_categories
  respond_to :html, :js
  before_action :all_items, only: [:index, :create, :destroy, :update]
  # GET /items
  # GET /items.json
  def index
    @search = Item.search(params[:q])
    @search.sorts = 'name asc' if @search.sorts.empty?
    @items = @search.result
     if params[:q].present?
        params[:q].each do |k, v| 
      if v == 'name asc'
        @items = @search.result.sort { |p1, p2| p1.name.downcase <=> p2.name.downcase }
      elsif v == 'name desc'
        @items = @search.result.sort { |p2, p1| p1.name.downcase <=> p2.name.downcase }
      end
    end
  end
  end

  def all_items
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    vendor = Vendor.find(item_params[:vendor_id])
    @item.build_vendor(:id => vendor.id)
    @item.save!
    @current_item = @item
    @items = Item.all
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.update!(item_params)
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :category)
    end
    def set_categories
      @categories = Item.categories
    end
    def item_params
        params.require(:item).permit(:name, :price, :category, :vendor_id)
    end   
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  before_action :all_vendors, only: [:index, :create, :destroy, :update]

  # GET /vendors
  # GET /vendors.json
  def index
    @search = Vendor.search(params[:q])
    @vendors = @search.result
  end

  def all_vendors
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)
    @vendor.save!
    @current_vendor = @vendor
    @vendor = Vendor.all
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    @vendor.update!(vendor_params)
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :email, :phone, :website, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def number_to_currency(number, options = {})
  options[:locale] ||= I18n.locale
  super(number, options)
end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/items/_edit.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Item</h4>
        <div class="modal-body">
        	<%= render 'form'%>
    	</div>
    </div>
</div>
</div>
</div>

app/views/items/_form.html.erb
<%= simple_form_for @item, remote: true, html: { class: "form-horizontal"} do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
       <ul>
          <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
       </ul>
    </div>
  <% end %>
    <div class="field">
       <%= f.label :name %><br>
       <%= f.text_field :name %>
    </div>
    <div class="field">
       <%= f.label :price %><br>
       <%= f.text_field :price %>
    </div>
    <div class="field">
       <%= f.label :category %><br>
       <%= f.select :category, options_for_select(@categories.collect {|s|
          [s[0].humanize, s[0]]}, selected: @item.category), {} %>
    </div>
    <div class="field">
       <%= f.label :vendor_id %><br>
       <%= f.select :vendor_id, options_for_select(Vendor.all.collect {|i| ["#{i.name}", i.id]}, selected: (@item.vendor ? @item.vendor.id : Vendor.first.id)), {} %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'button' %>
    </div>
<% end %>

app/views/items/_item.html.erb
    <% if item == @current_item %>
        <tr id="current_item">
    <% else %>
        <tr>
    <% end %>
<<<<<<< HEAD
        <td data-title="Name"><%= item.name.titleize %></td>
=======
        <td data-title="Name"><%= link_to(item.name.titleize, item, remote: true) %></td>
        <td data-title="Thumbnail"><%= image_tag item.thumbnail %></td>
>>>>>>> 43d33fd93abfe48b0c2bb984a8d5a46242bafa60
        <td data-title="Price"><%= number_to_currency(item.price) %></td>
        <td data-title="Category"><%= item.category %></td>
        <td data-title="Vendor"><a class="btn btn-default" <%= link_to(item.vendor.try(:name) || "NA", item.vendor, remote: true) %> </a> </td>
        <td data-title="Extra"><%= link_to edit_item_path(item),  class: 'btn btn-primary btn-xs', remote: true do%><i class="glyphicon glyphicon-edit"></i> Edit
        <% end %></td>
        <td data-title="Feature"><%= link_to item, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-danger btn-xs', remote: true do%><i class="glyphicon glyphicon-remove-circle"></i> Destroy<% end %></td>
    </tr>
    
    

app/views/items/_new.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Item</h4>
        <div class="modal-body">
        	<%= render 'form'%>
    	</div>
    </div>
</div>
</div>
</div>

app/views/items/_show.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Item</h4>
        <div class="modal-body">
        	<%= render 'form'%>
    	</div>
    </div>
</div>
</div>
</div>

app/views/items/create.js.erb
$('#items').html("<%= j (render @items) %>");
$('#myModal').modal('hide');
$('#current_item').css({'background-color' :
'#3c54e7'}).animate({'background-color' : '#ffffff'}, 1000);

app/views/items/destroy.js.erb
$('#items').html("<%= j (render @items) %>");

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/edit.js.erb
 $('#myModal').html('<%= escape_javascript(render 'edit') %>');
 $('#myModal').modal('show');

app/views/items/index.html.erb
<% if notice.present? %>
<p id="notice"><%= notice%></p>
<% end %>
<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<%= link_to new_item_path, id: 'myModal', class: 'btn btn-success', :"data-toggle" => 'modal', :"data-target" => '#myModal', remote: true do%>

</div>
<i class="glyphicon glyphicon-plus"></i> New Item

<% end %>

<h1>Listing Items</h1>

<br>
<%= search_form_for @search do |f| %>
  <div class ="field">
    <%= f.label :name_cont, "Name Contains:" %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="actions"><%= f.submit "Search" %> </div>
<% end %>

<div class="table-responsive">

<table class="table" id="no-more-tables">
  <thead>
    <tr>
      <th> <%= sort_link @search, :name, "Name" %></th>
      <th><%= sort_link @search, :price, "Price"  %></th>
      <th><%= sort_link @search, :category, "Category"  %></th>
      <th><%= sort_link @search, :vendor_name, "Vendor" %></th>
      <th colspan="2" >Extra Feature</th>
    </tr>
  </thead>
  <tbody id="items">
      <%= render @items %>
  </tbody>
</table>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/new.js.erb
 $('#myModal').html("<%= escape_javascript(render 'new') %>");
 $('#myModal').modal('show');

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
 <strong>Vendor:</strong>
 <%= (@item.vendor.try(:name) || "NA")%>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/show.js.erb
 $('#myModal').html('<%= escape_javascript(render 'show') %>');
 $('#myModal').modal('show');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
   	<meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Store</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
   </head>
   <body >
   <div class="container theme-showcase">
         <%= render 'shared/navigation' %>
         <div class="bs-docs-header" id="logo">
         </div>
   </div>
   <div class="container theme-showcase" role="main">
      <div id="main">
         <%= yield %>
      </div>
   </div>
   </body>
</html>

app/views/pages/api.html.erb
<h1>&nbsp;&nbsp;&nbsp;API</h1>
<div class="col-10">
	<div class="grey">
		<h2>Restful API </h2>
	</div>
<p id="col-11" class="big">Web service APIs that adhere to the REST architectural constraints are called RESTful APIs. HTTP based RESTful APIs are defined with these aspects: base URI, such as http://example.com/resources/ an Internet media type for the data.</p>
<div class="grey">
	<h3>GET</h3>
</div>
<a id="col-11" class="big" href="https://planetvapor.herokuapp.com/items.json">Item</a>
<br>
<br>
<a id="col-11" class="big" href="https://planetvapor.herokuapp.com/vendors.json">Vendor </a>
<div class="grey">
	<h3>Input</h3>
</div>
<p id="col-11" class="big">Use your favorite HTTP client tool to send a GET to the URL or click the links above. <br>
Link: https://planetvapor.herokuapp.com/items.json <br>
Link: https://planetvapor.herokuapp.com/vendors.json</p>
<div class="grey">
	<h3>Output</h3>
</div>
<p id="col-11" class="big">
	[
    { <br>
        "id": 11,
        "name": "cosmic charlie",
        "price": "6.50",
        "category": "Juice",
        "url": "https://planetvapor.herokuapp.com/items/11.json"
    },<br>
    {<br>
        "id": 12,
        "name": "high voltage",
        "price": "7.00",
        "category": "Juice",
        "url": "https://planetvapor.herokuapp.com/items/12.json"
    },<br>
    {<br>
        "id": 16,
        "name": "juice bottles",
        "price": "2.25",
        "category": "Accessories",
        "url": "https://planetvapor.herokuapp.com/items/16.json"
    },<br>
    {<br>
        "id": 17,
        "name": "kanger coils",
        "price": "0.75",
        "category": "Accessories",
        "url": "https://planetvapor.herokuapp.com/items/17.json"
    },<br>
    {<br>
        "id": 14,
        "name": "kangertech subtank",
        "price": "27.99",
        "category": "Battery",
        "url": "https://planetvapor.herokuapp.com/items/14.json"
    },<br>
    {<br>
        "id": 13,
        "name": "smy box mod",
        "price": "80.00",
        "category": "Mods",
        "url": "https://planetvapor.herokuapp.com/items/13.json"
    },<br>
    {<br>
        "id": 15,
        "name": "syringes",
        "price": "1.25",
        "category": "Accessories",
        "url": "https://planetvapor.herokuapp.com/items/15.json"
    }
]
</p>
</div>

app/views/shared/_navigation.html.erb
 <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" <%= link_to "Planet Vapor", items_path %> </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a <%= link_to "Home", items_path %> </a> </li>
 <li><a <%= link_to "Vendors", vendors_path %> </a> </li>
 <li><a <%= link_to "API", page_path('api') %> </a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
    </nav>

app/views/vendors/_edit.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Vendor</h4>
        <div class="modal-body">
        	<%= render 'form'%>
    	</div>
    </div>
</div>
</div>
</div>

app/views/vendors/_form.html.erb
<%= simple_form_for @vendor, remote: true, html: { class: "form-horizontal"} do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button'%>
  </div>
<% end %>

app/views/vendors/_new.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Vendor</h4>
        <div class="modal-body">
        	<%= render 'form'%>
    	</div>
    </div>
</div>
</div>
</div>

app/views/vendors/_show.html.erb
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Vendor</h4>
        <div class="modal-body">
        	<%= render 'form'%>
    	</div>
    </div>
</div>
</div>
</div>

app/views/vendors/_vendor.html.erb
      <tr>
        <td data-title="Name"><a class="btn btn-default" <%= link_to(vendor.name.titleize, vendor, remote: true) %> </a></td>
        <td data-title="Email"><%= vendor.email %></td>
        <td data-title="Phone"><%= vendor.phone %></td>
        <td data-title="Website"><a class="btn btn-default"<%= link_to vendor.website, vendor.website %> </a> </td>
        <td data-title="Country"><%= vendor.country %></td>
        <td data-title="Extra"><%= link_to edit_vendor_path(vendor),  class: 'btn btn-primary btn-xs', remote: true do%><i class="glyphicon glyphicon-edit"></i> Edit
        <% end %></td>
        <td data-title="Feature"><%= link_to vendor, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-danger btn-xs', remote: true do%><i class="glyphicon glyphicon-remove-circle"></i> Destroy<% end %></td>
      </tr>

app/views/vendors/create.js.erb
$('#vendors').html("<%= j (render @vendors) %>");
$('#myModal').modal('hide');

app/views/vendors/destroy.js.erb
$('#vendors').html("<%= j (render @vendors) %>");

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/edit.js.erb
 $('#myModal').html('<%= escape_javascript(render 'edit') %>');
 $('#myModal').modal('show');

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<%= link_to new_vendor_path, id: 'myModal', class: 'btn btn-success', :"data-toggle" => 'modal', :"data-target" => '#myModal', remote: true do%>
 
</div>
<i class="glyphicon glyphicon-plus"></i> New Vendor
<% end %>

<h1>Listing Vendors</h1>
<br>
<%= search_form_for @search do |f| %>
  <div class ="field">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="actions"><%= f.submit "Search" %> </div>
<% end %>
<div class="table-responsive">
<table class="table" id="no-more-table">
  <thead>
    <tr>
      <th><%= sort_link @search, :name, "Name"  %></th>
      <th>Email</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Country</th>
      <th colspan="2">Extra Feature</th>
    </tr>
  </thead>

  <tbody id="vendors">
    <%= render @vendors %>
  </tbody>
</table>
</div>
<br>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/new.js.erb
 $('#myModal').html('<%= escape_javascript(render 'new') %>');
 $('#myModal').modal('show');

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vendor.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vendor.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @vendor.website %>
</p>

<p>
  <strong>Country:</strong>
  <%= @vendor.country %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/update.js.erb
$('#vendors').html("<%= j (render @vendors) %>");
$('#myModal').modal('hide');